version: '3'

services:
  status-service:
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - 8000:8000
    volumes:
      - .:/app

  status-db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: status-service
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 3000:3306
