FROM python:3.7.16-slim
WORKDIR /app

# ENV SECRET_KEY=abcdefghijklmnopqrstuvwxyz
# ENV JWT_KEY=abcdefghijklmnopqrstuvwxyz
# ENV EMAIL_HOST_USER=sarveshpatkartech@gmail.com
# ENV EMAIL_HOST_PASSWORD=jlbqpgiqaxidwqwy

RUN pip install --upgrade pip 
COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY . .
EXPOSE 8000
CMD ["python3", "manage.py", "runserver", "0.0.0.0:8000"]