version: '3'

services:
  auth-service:
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - 8000:8000
    volumes:
      - .:/app

  auth-db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: auth-service
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33066:3306
